### ISSUE TITLE
Motor spin on boot.

### ISSUE THREAD

**Issue by carturn** [RoboticsTeam4904/2016-Code#15]
`new-motors` spins motors on boot.

**Comment by c0d3rman** [comment]
More specifically some of the intake motors (not the drive motors). We should test and document exactly which ones.

**Comment by carturn** [comment]
I think the motor-fixes pull request resolved this. The issue was related to voltage ramping "catching up" for all time since the Unix epoch. Voltage ramping is no longer allowed to increase the speed of a motor above the requested speed.

**Comment by c0d3rman** [comment]
@carturn Can you link the PR? Then (once we test on Pinkie before and after the commits) we'll close it.

**Comment by carturn** [comment]
This was RoboticsTeam4904/standard#64. It has already been tested.
