### ISSUE TITLE
Add exception logging to LogKitten

### ISSUE THREAD

**Issue by oldgalileo** [RoboticsTeam4904/2016-Code#40]
### Proposed

Add exception logging capabilities to LogKitten to print the full stack trace of an exception.
### Why

Currently if you want to print the exception to LogKitten you have to loop through the entire stackTrace and that creates at least 4 lines of redundant code that should be handled by LogKitten.
### To-do

@HowardStark (still me) will add a specific print exception method in LogKitten, which we can add additional functionality to later.

**Comment by c0d3rman** [comment]
This should've been an issue on standard.
Done on RoboticsTeam4904/standard#68.
